---
# Copyright 2016, Logan Vig <logan2211@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Add BIRD yum key
  rpm_key:
    state: present
    key: "{{ bird_keys }}"
  register: add_keys
  until: add_keys is success
  retries: 5
  delay: 2
  when:
    - bird_package_source == 'bird'
  tags:
    - bird-keys

- name: Add BIRD repo
  zypper_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    autorefresh: true
    repo: "{{ item.baseurl }}"
    enabled: "{{ item.enabled | default(omit) }}"
    priority: "{{ item.priority | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  register: add_repos
  until: add_repos is success
  retries: 5
  delay: 2
  loop:
    - "{{ bird_repo }}"
  when:
    - bird_package_source == 'bird'
  tags:
    - bird-repos

- name: Disable repo metadata GPG check for BIRD
  command: "zypper mr --gpgcheck-allow-unsigned-repo --refresh {{ item.name }}"
  changed_when: false
  loop:
    - "{{ bird_repo }}"
  when:
    - bird_package_source == 'bird'
    - not item.repo_gpg_check | default('yes') | bool
  tags:
    - bird-repos
